interface Hoteis  {
  img1:string,
  img2:string,
  title:string,
  descricao:string,
  infoAdicionalQuarto:number,
  infoAdicionalHospedes:number,
  infoAdicionalNota:number,
  infoAdicionalPets:string,
  vejaMaisAdicional: string,
}

export const ListaDeHoteis: Array<Hoteis> = [
 {
  img1: './rj-1-p.jpg',
  img2: 'rj-2.jpg',
  title: 'Copacabana Palace',
  descricao: 'O Hotel Copacabana Palace é um hotel de luxo localizado na Praia de Copacabana, no Rio de Janeiro, Brasil. Fundado em 1923, é considerado um ícone da cidade e um dos hotéis mais famosos do Brasil. Possui quartos e suítes luxuosos, piscina ao ar livre, spa, academia,restaurantes renomados e vista para a praia.',
  infoAdicionalQuarto:212,
  infoAdicionalHospedes:514,
  infoAdicionalNota:9.8,
  infoAdicionalPets:'Sim',
  vejaMaisAdicional:'hotel-rj',
 },
 {
  img1: './disney-1-p.jpg',
  img2: 'disney-2.jpg',
  title: 'Homewood Suites',
  descricao: 'Localizado a 8,6 km do Disney`s Boardwalk, o Homewood Suites by Hilton Orlando Flamingo Crossings, oferece acomodações 3 estrelas em Orlando e dispõe de churrasqueira',
  infoAdicionalQuarto:515,
  infoAdicionalHospedes:986,
  infoAdicionalNota:9.9,
  infoAdicionalPets:'Sim',
  vejaMaisAdicional:'hotel-disney',
 },
 {
  img1: './punta-caribe-1-p.jpg',
  img2: 'punta-caribe-2.jpg',
  title: 'Punta Cana Hotel',
  descricao: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas nihil deserunt dolore accusantium deleniti voluptate vero velit, in consequatur minus officiis voluptatem quia non impedit veritatis .',
  infoAdicionalQuarto:125,
  infoAdicionalHospedes:267,
  infoAdicionalNota:9.5,
  infoAdicionalPets:'Sim',
  vejaMaisAdicional:'hotel-caribe',
 },
 {
  img1: './canada-1-p.jpg',
  img2: 'canada-2.jpg',
  title: 'Canadá Hotel',
  descricao: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas nihil deserunt dolore accusantium deleniti voluptate vero velit, in consequatur minus officiis voluptatem quia non impedit veritatis .',
  infoAdicionalQuarto:197,
  infoAdicionalHospedes:428,
  infoAdicionalNota:9.6,
  infoAdicionalPets:'Sim',
  vejaMaisAdicional:'hotel-canada',
 },
 {
  img1: './suica-1-p.jpg',
  img2: 'suica-2.jpg',
  title: 'Suiça Hotel',
  descricao: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas nihil deserunt dolore accusantium deleniti voluptate vero velit, in consequatur minus officiis voluptatem quia non impedit veritatis .',
  infoAdicionalQuarto:197,
  infoAdicionalHospedes:428,
  infoAdicionalNota:9.6,
  infoAdicionalPets:'Sim',
  vejaMaisAdicional:'hotel-suica',
 },
 {
  img1: './londres-1-p.jpg',
  img2: 'londres-2.jpeg',
  title: 'Londres Hotel',
  descricao: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas nihil deserunt dolore accusantium deleniti voluptate vero velit, in consequatur minus officiis voluptatem quia non impedit veritatis .',
  infoAdicionalQuarto:197,
  infoAdicionalHospedes:428,
  infoAdicionalNota:9.6,
  infoAdicionalPets:'Sim',
  vejaMaisAdicional:'hotel-londres',
 },
]